
package csdc.tool.webService.smdb.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://server.webService.service.csdc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operate", targetNamespace = "http://server.webService.service.csdc/", className = "csdc.tool.webService.smdb.jaxws.Operate")
    @ResponseWrapper(localName = "operateResponse", targetNamespace = "http://server.webService.service.csdc/", className = "csdc.tool.webService.smdb.jaxws.OperateResponse")
    public String operate(
        @WebParam(name = "arg0", targetNamespace = "http://csdc.info/")
        String arg0);

}
